# Generated by Django 5.0.2 on 2024-03-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_partneroffer_post_court_post_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
