# Generated by Django 5.0.2 on 2024-04-01 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='responders',
            field=models.ManyToManyField(related_name='responded_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
