# Generated by Django 5.0.2 on 2024-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_responder'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game_type',
            field=models.CharField(choices=[('Новичок', 'Новичок'), ('Профи', 'Профи'), ('Любительская игра', 'Любительская игра'), ('Турнир', 'Турнир')], default='Новичок', max_length=20, verbose_name='Тип игры'),
        ),
    ]
